# Generated by Django 4.1.7 on 2023-03-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('art', 'Art'), ('biography', 'Biography'), ('business', 'Business'), ('classics', 'Classics'), ('education', 'Education'), ('graphic novel', 'Graphic Novel'), ('history', 'History'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('philosophy', 'Philosophy'), ('romance', 'Romance'), ('thriller', 'Thriller')], max_length=50),
        ),
    ]
