# Generated by Django 4.1.7 on 2023-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_author_bio_author_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('art', 'Art'), ('biography', 'Biography'), ('business', 'Business'), ('classics', 'Classics'), ('education', 'Education'), ('graphic novel', 'Graphic Novel'), ('history', 'History'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('philosophy', 'Philosophy'), ('romance', 'Romance'), ('thriller', 'Thriller')], max_length=100),
        ),
    ]
