# Generated by Django 4.1.7 on 2023-03-22 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_blurb_alter_author_bio_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('art', 'Art'), ('biography', 'Biography'), ('business', 'Business'), ('classics', 'Classics'), ('education', 'Education'), ('graphic novel', 'Graphic Novel'), ('history', 'History'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('philosophy', 'Philosophy'), ('religion', 'Religion'), ('romance', 'Romance'), ('thriller', 'Thriller')], max_length=100),
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want to read', 'Want to Read'), ('reading', 'Reading'), ('finished', 'Finished')], max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
