# Generated by Django 4.1.7 on 2023-03-23 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_constraint',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_instances', to='core.book'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='book_constraint'),
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='tracker_constraint'),
        ),
    ]
