# Generated by Django 4.1.7 on 2023-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_book_unique_constraint_alter_tracker_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_published',
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
