# Generated by Django 4.1.7 on 2023-03-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_book_date_published_book_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
