# Generated by Django 4.1.7 on 2023-03-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_author_bio_alter_book_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
