# Generated by Django 4.1.7 on 2023-03-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_author_bio_alter_book_blurb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
