# Generated by Django 4.1.7 on 2023-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('', ''), ('art', 'Art'), ('biography', 'Biography'), ('business', 'Business'), ('dystopian fiction', 'Dystopian Fiction'), ('classics', 'Classics'), ('education', 'Education'), ('fantasy', 'Fantasy'), ('graphic novel', 'Graphic Novel'), ('history', 'History'), ('horror', 'Horror'), ('kids lit', 'Kids Lit'), ('mystery', 'Mystery'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('religion', 'Religion'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('other', 'Other')], max_length=100),
        ),
    ]
