# Generated by Django 4.1.7 on 2023-03-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
