# Generated by Django 4.1.7 on 2023-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_author_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name',), name='author_constraint'),
        ),
    ]
