# Generated by Django 4.1.7 on 2023-03-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_featuredbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_book_instances', to='core.book'),
        ),
        migrations.AddConstraint(
            model_name='featuredbook',
            constraint=models.UniqueConstraint(fields=('book',), name='featured_book_constraint'),
        ),
    ]
