# Generated by Django 4.1.7 on 2023-03-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_featuredbook_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedBook',
        ),
    ]
